// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.instruments;

import com.lacunalabs.dm.data.physics.instruments.CcdCamera;
import com.lacunalabs.dm.data.physics.instruments.CcdCameraDataOnDemand;
import com.lacunalabs.dm.data.repository.physics.instruments.CcdCameraService;
import com.lacunalabs.dm.shared.physics.fundamental.MetaDataType;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CcdCameraDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CcdCameraDataOnDemand: @Component;
    
    private Random CcdCameraDataOnDemand.rnd = new SecureRandom();
    
    private List<CcdCamera> CcdCameraDataOnDemand.data;
    
    @Autowired
    CcdCameraService CcdCameraDataOnDemand.ccdCameraService;
    
    public CcdCamera CcdCameraDataOnDemand.getNewTransientCcdCamera(int index) {
        CcdCamera obj = new CcdCamera();
        setCollectionEfficiency(obj, index);
        setManufacturer(obj, index);
        setMetadata(obj, index);
        setMetadataType(obj, index);
        setName(obj, index);
        setXResolution(obj, index);
        setYResolution(obj, index);
        return obj;
    }
    
    public void CcdCameraDataOnDemand.setCollectionEfficiency(CcdCamera obj, int index) {
        BigDecimal collectionEfficiency = BigDecimal.valueOf(index);
        obj.setCollectionEfficiency(collectionEfficiency);
    }
    
    public void CcdCameraDataOnDemand.setManufacturer(CcdCamera obj, int index) {
        String manufacturer = "manufacturer_" + index;
        obj.setManufacturer(manufacturer);
    }
    
    public void CcdCameraDataOnDemand.setMetadata(CcdCamera obj, int index) {
        String metadata = "metadata_" + index;
        obj.setMetadata(metadata);
    }
    
    public void CcdCameraDataOnDemand.setMetadataType(CcdCamera obj, int index) {
        MetaDataType metadataType = MetaDataType.class.getEnumConstants()[0];
        obj.setMetadataType(metadataType);
    }
    
    public void CcdCameraDataOnDemand.setName(CcdCamera obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void CcdCameraDataOnDemand.setXResolution(CcdCamera obj, int index) {
        Integer xResolution = new Integer(index);
        obj.setXResolution(xResolution);
    }
    
    public void CcdCameraDataOnDemand.setYResolution(CcdCamera obj, int index) {
        Integer yResolution = new Integer(index);
        obj.setYResolution(yResolution);
    }
    
    public CcdCamera CcdCameraDataOnDemand.getSpecificCcdCamera(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CcdCamera obj = data.get(index);
        BigInteger id = obj.getId();
        return ccdCameraService.findCcdCamera(id);
    }
    
    public CcdCamera CcdCameraDataOnDemand.getRandomCcdCamera() {
        init();
        CcdCamera obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return ccdCameraService.findCcdCamera(id);
    }
    
    public boolean CcdCameraDataOnDemand.modifyCcdCamera(CcdCamera obj) {
        return false;
    }
    
    public void CcdCameraDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ccdCameraService.findCcdCameraEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CcdCamera' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CcdCamera>();
        for (int i = 0; i < 10; i++) {
            CcdCamera obj = getNewTransientCcdCamera(i);
            try {
                ccdCameraService.saveCcdCamera(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
