// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.instruments;

import com.lacunalabs.dm.data.physics.instruments.TemDoubleTiltHolderDataOnDemand;
import com.lacunalabs.dm.data.physics.instruments.TemDoubleTiltHolderIntegrationTest;
import com.lacunalabs.dm.data.repository.physics.instruments.TemDoubleTiltHolderService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect TemDoubleTiltHolderIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TemDoubleTiltHolderIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TemDoubleTiltHolderIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private TemDoubleTiltHolderDataOnDemand TemDoubleTiltHolderIntegrationTest.dod;
    
    @Autowired
    TemDoubleTiltHolderService TemDoubleTiltHolderIntegrationTest.temDoubleTiltHolderService;
    
    @Test
    public void TemDoubleTiltHolderIntegrationTest.testCountAllTemDoubleTiltHolders() {
        Assert.assertNotNull("Data on demand for 'TemDoubleTiltHolder' failed to initialize correctly", dod.getRandomTemDoubleTiltHolder());
        long count = temDoubleTiltHolderService.countAllTemDoubleTiltHolders();
        Assert.assertTrue("Counter for 'TemDoubleTiltHolder' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TemDoubleTiltHolderIntegrationTest.testFindTemDoubleTiltHolder() {
        TemDoubleTiltHolder obj = dod.getRandomTemDoubleTiltHolder();
        Assert.assertNotNull("Data on demand for 'TemDoubleTiltHolder' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TemDoubleTiltHolder' failed to provide an identifier", id);
        obj = temDoubleTiltHolderService.findTemDoubleTiltHolder(id);
        Assert.assertNotNull("Find method for 'TemDoubleTiltHolder' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TemDoubleTiltHolder' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TemDoubleTiltHolderIntegrationTest.testFindAllTemDoubleTiltHolders() {
        Assert.assertNotNull("Data on demand for 'TemDoubleTiltHolder' failed to initialize correctly", dod.getRandomTemDoubleTiltHolder());
        long count = temDoubleTiltHolderService.countAllTemDoubleTiltHolders();
        Assert.assertTrue("Too expensive to perform a find all test for 'TemDoubleTiltHolder', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TemDoubleTiltHolder> result = temDoubleTiltHolderService.findAllTemDoubleTiltHolders();
        Assert.assertNotNull("Find all method for 'TemDoubleTiltHolder' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TemDoubleTiltHolder' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TemDoubleTiltHolderIntegrationTest.testFindTemDoubleTiltHolderEntries() {
        Assert.assertNotNull("Data on demand for 'TemDoubleTiltHolder' failed to initialize correctly", dod.getRandomTemDoubleTiltHolder());
        long count = temDoubleTiltHolderService.countAllTemDoubleTiltHolders();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TemDoubleTiltHolder> result = temDoubleTiltHolderService.findTemDoubleTiltHolderEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TemDoubleTiltHolder' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TemDoubleTiltHolder' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TemDoubleTiltHolderIntegrationTest.testSaveTemDoubleTiltHolder() {
        Assert.assertNotNull("Data on demand for 'TemDoubleTiltHolder' failed to initialize correctly", dod.getRandomTemDoubleTiltHolder());
        TemDoubleTiltHolder obj = dod.getNewTransientTemDoubleTiltHolder(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TemDoubleTiltHolder' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TemDoubleTiltHolder' identifier to be null", obj.getId());
        temDoubleTiltHolderService.saveTemDoubleTiltHolder(obj);
        Assert.assertNotNull("Expected 'TemDoubleTiltHolder' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TemDoubleTiltHolderIntegrationTest.testDeleteTemDoubleTiltHolder() {
        TemDoubleTiltHolder obj = dod.getRandomTemDoubleTiltHolder();
        Assert.assertNotNull("Data on demand for 'TemDoubleTiltHolder' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TemDoubleTiltHolder' failed to provide an identifier", id);
        obj = temDoubleTiltHolderService.findTemDoubleTiltHolder(id);
        temDoubleTiltHolderService.deleteTemDoubleTiltHolder(obj);
        Assert.assertNull("Failed to remove 'TemDoubleTiltHolder' with identifier '" + id + "'", temDoubleTiltHolderService.findTemDoubleTiltHolder(id));
    }
    
}
