// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.instruments;

import com.lacunalabs.dm.data.physics.instruments.TemDoubleTiltHolder;
import com.lacunalabs.dm.data.physics.instruments.TemDoubleTiltHolderDataOnDemand;
import com.lacunalabs.dm.data.repository.physics.instruments.TemDoubleTiltHolderService;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TemDoubleTiltHolderDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TemDoubleTiltHolderDataOnDemand: @Component;
    
    private Random TemDoubleTiltHolderDataOnDemand.rnd = new SecureRandom();
    
    private List<TemDoubleTiltHolder> TemDoubleTiltHolderDataOnDemand.data;
    
    @Autowired
    TemDoubleTiltHolderService TemDoubleTiltHolderDataOnDemand.temDoubleTiltHolderService;
    
    public TemDoubleTiltHolder TemDoubleTiltHolderDataOnDemand.getNewTransientTemDoubleTiltHolder(int index) {
        TemDoubleTiltHolder obj = new TemDoubleTiltHolder();
        setAzimuthAxisRotationToVertical(obj, index);
        setName(obj, index);
        setTiltAxisRotationToVertical(obj, index);
        return obj;
    }
    
    public void TemDoubleTiltHolderDataOnDemand.setAzimuthAxisRotationToVertical(TemDoubleTiltHolder obj, int index) {
        BigDecimal azimuthAxisRotationToVertical = BigDecimal.valueOf(index);
        obj.setAzimuthAxisRotationToVertical(azimuthAxisRotationToVertical);
    }
    
    public void TemDoubleTiltHolderDataOnDemand.setName(TemDoubleTiltHolder obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void TemDoubleTiltHolderDataOnDemand.setTiltAxisRotationToVertical(TemDoubleTiltHolder obj, int index) {
        BigDecimal tiltAxisRotationToVertical = BigDecimal.valueOf(index);
        obj.setTiltAxisRotationToVertical(tiltAxisRotationToVertical);
    }
    
    public TemDoubleTiltHolder TemDoubleTiltHolderDataOnDemand.getSpecificTemDoubleTiltHolder(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TemDoubleTiltHolder obj = data.get(index);
        BigInteger id = obj.getId();
        return temDoubleTiltHolderService.findTemDoubleTiltHolder(id);
    }
    
    public TemDoubleTiltHolder TemDoubleTiltHolderDataOnDemand.getRandomTemDoubleTiltHolder() {
        init();
        TemDoubleTiltHolder obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return temDoubleTiltHolderService.findTemDoubleTiltHolder(id);
    }
    
    public boolean TemDoubleTiltHolderDataOnDemand.modifyTemDoubleTiltHolder(TemDoubleTiltHolder obj) {
        return false;
    }
    
    public void TemDoubleTiltHolderDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = temDoubleTiltHolderService.findTemDoubleTiltHolderEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TemDoubleTiltHolder' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TemDoubleTiltHolder>();
        for (int i = 0; i < 10; i++) {
            TemDoubleTiltHolder obj = getNewTransientTemDoubleTiltHolder(i);
            try {
                temDoubleTiltHolderService.saveTemDoubleTiltHolder(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
