// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.instruments;

import com.lacunalabs.dm.data.physics.instruments.TemIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TemIntegrationTest_Roo_Configurable {
    
    declare @type: TemIntegrationTest: @Configurable;
    
}
