// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.solidstate;

import com.lacunalabs.dm.data.physics.solidstate.CrystalPhysicalPropertyDataOnDemand;
import com.lacunalabs.dm.data.physics.solidstate.CrystalPhysicalPropertyIntegrationTest;
import com.lacunalabs.dm.data.repository.physics.solidstate.CrystalPhysicalPropertyService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect CrystalPhysicalPropertyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CrystalPhysicalPropertyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CrystalPhysicalPropertyIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private CrystalPhysicalPropertyDataOnDemand CrystalPhysicalPropertyIntegrationTest.dod;
    
    @Autowired
    CrystalPhysicalPropertyService CrystalPhysicalPropertyIntegrationTest.crystalPhysicalPropertyService;
    
    @Test
    public void CrystalPhysicalPropertyIntegrationTest.testCountAllCrystalPhysicalPropertys() {
        Assert.assertNotNull("Data on demand for 'CrystalPhysicalProperty' failed to initialize correctly", dod.getRandomCrystalPhysicalProperty());
        long count = crystalPhysicalPropertyService.countAllCrystalPhysicalPropertys();
        Assert.assertTrue("Counter for 'CrystalPhysicalProperty' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CrystalPhysicalPropertyIntegrationTest.testFindCrystalPhysicalProperty() {
        CrystalPhysicalProperty obj = dod.getRandomCrystalPhysicalProperty();
        Assert.assertNotNull("Data on demand for 'CrystalPhysicalProperty' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CrystalPhysicalProperty' failed to provide an identifier", id);
        obj = crystalPhysicalPropertyService.findCrystalPhysicalProperty(id);
        Assert.assertNotNull("Find method for 'CrystalPhysicalProperty' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CrystalPhysicalProperty' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CrystalPhysicalPropertyIntegrationTest.testFindAllCrystalPhysicalPropertys() {
        Assert.assertNotNull("Data on demand for 'CrystalPhysicalProperty' failed to initialize correctly", dod.getRandomCrystalPhysicalProperty());
        long count = crystalPhysicalPropertyService.countAllCrystalPhysicalPropertys();
        Assert.assertTrue("Too expensive to perform a find all test for 'CrystalPhysicalProperty', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CrystalPhysicalProperty> result = crystalPhysicalPropertyService.findAllCrystalPhysicalPropertys();
        Assert.assertNotNull("Find all method for 'CrystalPhysicalProperty' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CrystalPhysicalProperty' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CrystalPhysicalPropertyIntegrationTest.testFindCrystalPhysicalPropertyEntries() {
        Assert.assertNotNull("Data on demand for 'CrystalPhysicalProperty' failed to initialize correctly", dod.getRandomCrystalPhysicalProperty());
        long count = crystalPhysicalPropertyService.countAllCrystalPhysicalPropertys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CrystalPhysicalProperty> result = crystalPhysicalPropertyService.findCrystalPhysicalPropertyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CrystalPhysicalProperty' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CrystalPhysicalProperty' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CrystalPhysicalPropertyIntegrationTest.testSaveCrystalPhysicalProperty() {
        Assert.assertNotNull("Data on demand for 'CrystalPhysicalProperty' failed to initialize correctly", dod.getRandomCrystalPhysicalProperty());
        CrystalPhysicalProperty obj = dod.getNewTransientCrystalPhysicalProperty(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CrystalPhysicalProperty' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CrystalPhysicalProperty' identifier to be null", obj.getId());
        crystalPhysicalPropertyService.saveCrystalPhysicalProperty(obj);
        Assert.assertNotNull("Expected 'CrystalPhysicalProperty' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CrystalPhysicalPropertyIntegrationTest.testDeleteCrystalPhysicalProperty() {
        CrystalPhysicalProperty obj = dod.getRandomCrystalPhysicalProperty();
        Assert.assertNotNull("Data on demand for 'CrystalPhysicalProperty' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CrystalPhysicalProperty' failed to provide an identifier", id);
        obj = crystalPhysicalPropertyService.findCrystalPhysicalProperty(id);
        crystalPhysicalPropertyService.deleteCrystalPhysicalProperty(obj);
        Assert.assertNull("Failed to remove 'CrystalPhysicalProperty' with identifier '" + id + "'", crystalPhysicalPropertyService.findCrystalPhysicalProperty(id));
    }
    
}
