// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.solidstate;

import com.lacunalabs.dm.data.physics.solidstate.MaterialDataOnDemand;
import com.lacunalabs.dm.data.physics.solidstate.MaterialIntegrationTest;
import com.lacunalabs.dm.data.repository.physics.solidstate.MaterialService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect MaterialIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MaterialIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MaterialIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private MaterialDataOnDemand MaterialIntegrationTest.dod;
    
    @Autowired
    MaterialService MaterialIntegrationTest.materialService;
    
    @Test
    public void MaterialIntegrationTest.testCountAllMaterials() {
        Assert.assertNotNull("Data on demand for 'Material' failed to initialize correctly", dod.getRandomMaterial());
        long count = materialService.countAllMaterials();
        Assert.assertTrue("Counter for 'Material' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MaterialIntegrationTest.testFindMaterial() {
        Material obj = dod.getRandomMaterial();
        Assert.assertNotNull("Data on demand for 'Material' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Material' failed to provide an identifier", id);
        obj = materialService.findMaterial(id);
        Assert.assertNotNull("Find method for 'Material' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Material' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MaterialIntegrationTest.testFindAllMaterials() {
        Assert.assertNotNull("Data on demand for 'Material' failed to initialize correctly", dod.getRandomMaterial());
        long count = materialService.countAllMaterials();
        Assert.assertTrue("Too expensive to perform a find all test for 'Material', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Material> result = materialService.findAllMaterials();
        Assert.assertNotNull("Find all method for 'Material' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Material' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MaterialIntegrationTest.testFindMaterialEntries() {
        Assert.assertNotNull("Data on demand for 'Material' failed to initialize correctly", dod.getRandomMaterial());
        long count = materialService.countAllMaterials();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Material> result = materialService.findMaterialEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Material' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Material' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MaterialIntegrationTest.testSaveMaterial() {
        Assert.assertNotNull("Data on demand for 'Material' failed to initialize correctly", dod.getRandomMaterial());
        Material obj = dod.getNewTransientMaterial(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Material' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Material' identifier to be null", obj.getId());
        materialService.saveMaterial(obj);
        Assert.assertNotNull("Expected 'Material' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MaterialIntegrationTest.testDeleteMaterial() {
        Material obj = dod.getRandomMaterial();
        Assert.assertNotNull("Data on demand for 'Material' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Material' failed to provide an identifier", id);
        obj = materialService.findMaterial(id);
        materialService.deleteMaterial(obj);
        Assert.assertNull("Failed to remove 'Material' with identifier '" + id + "'", materialService.findMaterial(id));
    }
    
}
