// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.solidstate;

import com.lacunalabs.dm.data.physics.solidstate.MaterialComponentDataOnDemand;
import com.lacunalabs.dm.data.physics.solidstate.MaterialComponentOrientations;
import com.lacunalabs.dm.data.physics.solidstate.MaterialComponentOrientationsDataOnDemand;
import com.lacunalabs.dm.data.repository.physics.solidstate.MaterialComponentOrientationsService;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MaterialComponentOrientationsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MaterialComponentOrientationsDataOnDemand: @Component;
    
    private Random MaterialComponentOrientationsDataOnDemand.rnd = new SecureRandom();
    
    private List<MaterialComponentOrientations> MaterialComponentOrientationsDataOnDemand.data;
    
    @Autowired
    private MaterialComponentDataOnDemand MaterialComponentOrientationsDataOnDemand.materialComponentDataOnDemand;
    
    @Autowired
    MaterialComponentOrientationsService MaterialComponentOrientationsDataOnDemand.materialComponentOrientationsService;
    
    public MaterialComponentOrientations MaterialComponentOrientationsDataOnDemand.getNewTransientMaterialComponentOrientations(int index) {
        MaterialComponentOrientations obj = new MaterialComponentOrientations();
        return obj;
    }
    
    public MaterialComponentOrientations MaterialComponentOrientationsDataOnDemand.getSpecificMaterialComponentOrientations(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        MaterialComponentOrientations obj = data.get(index);
        BigInteger id = obj.getId();
        return materialComponentOrientationsService.findMaterialComponentOrientations(id);
    }
    
    public MaterialComponentOrientations MaterialComponentOrientationsDataOnDemand.getRandomMaterialComponentOrientations() {
        init();
        MaterialComponentOrientations obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return materialComponentOrientationsService.findMaterialComponentOrientations(id);
    }
    
    public boolean MaterialComponentOrientationsDataOnDemand.modifyMaterialComponentOrientations(MaterialComponentOrientations obj) {
        return false;
    }
    
    public void MaterialComponentOrientationsDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = materialComponentOrientationsService.findMaterialComponentOrientationsEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'MaterialComponentOrientations' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<MaterialComponentOrientations>();
        for (int i = 0; i < 10; i++) {
            MaterialComponentOrientations obj = getNewTransientMaterialComponentOrientations(i);
            try {
                materialComponentOrientationsService.saveMaterialComponentOrientations(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
