// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.solidstate;

import com.lacunalabs.dm.data.physics.fundamental.PhysicalPropertyTypeDataOnDemand;
import com.lacunalabs.dm.data.physics.solidstate.MaterialDataOnDemand;
import com.lacunalabs.dm.data.physics.solidstate.MaterialPhysicalProperty;
import com.lacunalabs.dm.data.physics.solidstate.MaterialPhysicalPropertyDataOnDemand;
import com.lacunalabs.dm.data.repository.physics.solidstate.MaterialPhysicalPropertyService;
import com.lacunalabs.dm.shared.physics.fundamental.UncertaintyType;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MaterialPhysicalPropertyDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MaterialPhysicalPropertyDataOnDemand: @Component;
    
    private Random MaterialPhysicalPropertyDataOnDemand.rnd = new SecureRandom();
    
    private List<MaterialPhysicalProperty> MaterialPhysicalPropertyDataOnDemand.data;
    
    @Autowired
    private MaterialDataOnDemand MaterialPhysicalPropertyDataOnDemand.materialDataOnDemand;
    
    @Autowired
    private PhysicalPropertyTypeDataOnDemand MaterialPhysicalPropertyDataOnDemand.physicalPropertyTypeDataOnDemand;
    
    @Autowired
    MaterialPhysicalPropertyService MaterialPhysicalPropertyDataOnDemand.materialPhysicalPropertyService;
    
    public MaterialPhysicalProperty MaterialPhysicalPropertyDataOnDemand.getNewTransientMaterialPhysicalProperty(int index) {
        MaterialPhysicalProperty obj = new MaterialPhysicalProperty();
        setFunctionParameters(obj, index);
        setName(obj, index);
        setQuantity(obj, index);
        setUncertainty(obj, index);
        setUncertaintyType(obj, index);
        return obj;
    }
    
    public void MaterialPhysicalPropertyDataOnDemand.setFunctionParameters(MaterialPhysicalProperty obj, int index) {
        String functionParameters = "functionParameters_" + index;
        obj.setFunctionParameters(functionParameters);
    }
    
    public void MaterialPhysicalPropertyDataOnDemand.setName(MaterialPhysicalProperty obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void MaterialPhysicalPropertyDataOnDemand.setQuantity(MaterialPhysicalProperty obj, int index) {
        BigDecimal quantity = BigDecimal.valueOf(index);
        obj.setQuantity(quantity);
    }
    
    public void MaterialPhysicalPropertyDataOnDemand.setUncertainty(MaterialPhysicalProperty obj, int index) {
        BigDecimal uncertainty = BigDecimal.valueOf(index);
        obj.setUncertainty(uncertainty);
    }
    
    public void MaterialPhysicalPropertyDataOnDemand.setUncertaintyType(MaterialPhysicalProperty obj, int index) {
        UncertaintyType uncertaintyType = UncertaintyType.class.getEnumConstants()[0];
        obj.setUncertaintyType(uncertaintyType);
    }
    
    public MaterialPhysicalProperty MaterialPhysicalPropertyDataOnDemand.getSpecificMaterialPhysicalProperty(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        MaterialPhysicalProperty obj = data.get(index);
        BigInteger id = obj.getId();
        return materialPhysicalPropertyService.findMaterialPhysicalProperty(id);
    }
    
    public MaterialPhysicalProperty MaterialPhysicalPropertyDataOnDemand.getRandomMaterialPhysicalProperty() {
        init();
        MaterialPhysicalProperty obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return materialPhysicalPropertyService.findMaterialPhysicalProperty(id);
    }
    
    public boolean MaterialPhysicalPropertyDataOnDemand.modifyMaterialPhysicalProperty(MaterialPhysicalProperty obj) {
        return false;
    }
    
    public void MaterialPhysicalPropertyDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = materialPhysicalPropertyService.findMaterialPhysicalPropertyEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'MaterialPhysicalProperty' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<MaterialPhysicalProperty>();
        for (int i = 0; i < 10; i++) {
            MaterialPhysicalProperty obj = getNewTransientMaterialPhysicalProperty(i);
            try {
                materialPhysicalPropertyService.saveMaterialPhysicalProperty(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
