// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.crystallography;

import com.lacunalabs.dm.data.physics.crystallography.BravaisLatticeDataOnDemand;
import com.lacunalabs.dm.data.physics.crystallography.BravaisLatticeIntegrationTest;
import com.lacunalabs.dm.data.repository.physics.crystallography.BravaisLatticeService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect BravaisLatticeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BravaisLatticeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BravaisLatticeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private BravaisLatticeDataOnDemand BravaisLatticeIntegrationTest.dod;
    
    @Autowired
    BravaisLatticeService BravaisLatticeIntegrationTest.bravaisLatticeService;
    
    @Test
    public void BravaisLatticeIntegrationTest.testCountAllBravaisLattices() {
        Assert.assertNotNull("Data on demand for 'BravaisLattice' failed to initialize correctly", dod.getRandomBravaisLattice());
        long count = bravaisLatticeService.countAllBravaisLattices();
        Assert.assertTrue("Counter for 'BravaisLattice' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BravaisLatticeIntegrationTest.testFindBravaisLattice() {
        BravaisLattice obj = dod.getRandomBravaisLattice();
        Assert.assertNotNull("Data on demand for 'BravaisLattice' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BravaisLattice' failed to provide an identifier", id);
        obj = bravaisLatticeService.findBravaisLattice(id);
        Assert.assertNotNull("Find method for 'BravaisLattice' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'BravaisLattice' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BravaisLatticeIntegrationTest.testFindAllBravaisLattices() {
        Assert.assertNotNull("Data on demand for 'BravaisLattice' failed to initialize correctly", dod.getRandomBravaisLattice());
        long count = bravaisLatticeService.countAllBravaisLattices();
        Assert.assertTrue("Too expensive to perform a find all test for 'BravaisLattice', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<BravaisLattice> result = bravaisLatticeService.findAllBravaisLattices();
        Assert.assertNotNull("Find all method for 'BravaisLattice' illegally returned null", result);
        Assert.assertTrue("Find all method for 'BravaisLattice' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BravaisLatticeIntegrationTest.testFindBravaisLatticeEntries() {
        Assert.assertNotNull("Data on demand for 'BravaisLattice' failed to initialize correctly", dod.getRandomBravaisLattice());
        long count = bravaisLatticeService.countAllBravaisLattices();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<BravaisLattice> result = bravaisLatticeService.findBravaisLatticeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'BravaisLattice' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'BravaisLattice' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BravaisLatticeIntegrationTest.testSaveBravaisLattice() {
        Assert.assertNotNull("Data on demand for 'BravaisLattice' failed to initialize correctly", dod.getRandomBravaisLattice());
        BravaisLattice obj = dod.getNewTransientBravaisLattice(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'BravaisLattice' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'BravaisLattice' identifier to be null", obj.getId());
        bravaisLatticeService.saveBravaisLattice(obj);
        Assert.assertNotNull("Expected 'BravaisLattice' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BravaisLatticeIntegrationTest.testDeleteBravaisLattice() {
        BravaisLattice obj = dod.getRandomBravaisLattice();
        Assert.assertNotNull("Data on demand for 'BravaisLattice' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BravaisLattice' failed to provide an identifier", id);
        obj = bravaisLatticeService.findBravaisLattice(id);
        bravaisLatticeService.deleteBravaisLattice(obj);
        Assert.assertNull("Failed to remove 'BravaisLattice' with identifier '" + id + "'", bravaisLatticeService.findBravaisLattice(id));
    }
    
}
