// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.crystallography;

import com.lacunalabs.dm.data.physics.crystallography.CenteringDataOnDemand;
import com.lacunalabs.dm.data.physics.crystallography.CenteringIntegrationTest;
import com.lacunalabs.dm.data.repository.physics.crystallography.CenteringService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect CenteringIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CenteringIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CenteringIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private CenteringDataOnDemand CenteringIntegrationTest.dod;
    
    @Autowired
    CenteringService CenteringIntegrationTest.centeringService;
    
    @Test
    public void CenteringIntegrationTest.testCountAllCenterings() {
        Assert.assertNotNull("Data on demand for 'Centering' failed to initialize correctly", dod.getRandomCentering());
        long count = centeringService.countAllCenterings();
        Assert.assertTrue("Counter for 'Centering' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CenteringIntegrationTest.testFindCentering() {
        Centering obj = dod.getRandomCentering();
        Assert.assertNotNull("Data on demand for 'Centering' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Centering' failed to provide an identifier", id);
        obj = centeringService.findCentering(id);
        Assert.assertNotNull("Find method for 'Centering' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Centering' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CenteringIntegrationTest.testFindAllCenterings() {
        Assert.assertNotNull("Data on demand for 'Centering' failed to initialize correctly", dod.getRandomCentering());
        long count = centeringService.countAllCenterings();
        Assert.assertTrue("Too expensive to perform a find all test for 'Centering', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Centering> result = centeringService.findAllCenterings();
        Assert.assertNotNull("Find all method for 'Centering' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Centering' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CenteringIntegrationTest.testFindCenteringEntries() {
        Assert.assertNotNull("Data on demand for 'Centering' failed to initialize correctly", dod.getRandomCentering());
        long count = centeringService.countAllCenterings();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Centering> result = centeringService.findCenteringEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Centering' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Centering' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CenteringIntegrationTest.testSaveCentering() {
        Assert.assertNotNull("Data on demand for 'Centering' failed to initialize correctly", dod.getRandomCentering());
        Centering obj = dod.getNewTransientCentering(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Centering' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Centering' identifier to be null", obj.getId());
        centeringService.saveCentering(obj);
        Assert.assertNotNull("Expected 'Centering' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CenteringIntegrationTest.testDeleteCentering() {
        Centering obj = dod.getRandomCentering();
        Assert.assertNotNull("Data on demand for 'Centering' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Centering' failed to provide an identifier", id);
        obj = centeringService.findCentering(id);
        centeringService.deleteCentering(obj);
        Assert.assertNull("Failed to remove 'Centering' with identifier '" + id + "'", centeringService.findCentering(id));
    }
    
}
