// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.crystallography;

import com.lacunalabs.dm.data.physics.crystallography.CenteringDataOnDemand;
import com.lacunalabs.dm.data.physics.crystallography.PointGroup;
import com.lacunalabs.dm.data.physics.crystallography.PointGroupDataOnDemand;
import com.lacunalabs.dm.data.repository.physics.crystallography.PointGroupService;
import com.lacunalabs.dm.shared.physics.fundamental.MetaDataType;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PointGroupDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PointGroupDataOnDemand: @Component;
    
    private Random PointGroupDataOnDemand.rnd = new SecureRandom();
    
    private List<PointGroup> PointGroupDataOnDemand.data;
    
    @Autowired
    private CenteringDataOnDemand PointGroupDataOnDemand.centeringDataOnDemand;
    
    @Autowired
    PointGroupService PointGroupDataOnDemand.pointGroupService;
    
    public PointGroup PointGroupDataOnDemand.getNewTransientPointGroup(int index) {
        PointGroup obj = new PointGroup();
        setCenterings(obj, index);
        setCoordinatePoints(obj, index);
        setMetadata(obj, index);
        setMetadataType(obj, index);
        setName(obj, index);
        setReflectionConditions(obj, index);
        setSymbol(obj, index);
        return obj;
    }
    
    public void PointGroupDataOnDemand.setCenterings(PointGroup obj, int index) {
        String centerings = "centerings_" + index;
        obj.setCenterings(centerings);
    }
    
    public void PointGroupDataOnDemand.setCoordinatePoints(PointGroup obj, int index) {
        String coordinatePoints = "coordinatePoints_" + index;
        obj.setCoordinatePoints(coordinatePoints);
    }
    
    public void PointGroupDataOnDemand.setMetadata(PointGroup obj, int index) {
        String metadata = "metadata_" + index;
        obj.setMetadata(metadata);
    }
    
    public void PointGroupDataOnDemand.setMetadataType(PointGroup obj, int index) {
        MetaDataType metadataType = MetaDataType.class.getEnumConstants()[0];
        obj.setMetadataType(metadataType);
    }
    
    public void PointGroupDataOnDemand.setName(PointGroup obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void PointGroupDataOnDemand.setReflectionConditions(PointGroup obj, int index) {
        String reflectionConditions = "reflectionConditions_" + index;
        obj.setReflectionConditions(reflectionConditions);
    }
    
    public void PointGroupDataOnDemand.setSymbol(PointGroup obj, int index) {
        String symbol = "symbol_" + index;
        if (symbol.length() > 10) {
            symbol = symbol.substring(0, 10);
        }
        obj.setSymbol(symbol);
    }
    
    public PointGroup PointGroupDataOnDemand.getSpecificPointGroup(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PointGroup obj = data.get(index);
        BigInteger id = obj.getId();
        return pointGroupService.findPointGroup(id);
    }
    
    public PointGroup PointGroupDataOnDemand.getRandomPointGroup() {
        init();
        PointGroup obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return pointGroupService.findPointGroup(id);
    }
    
    public boolean PointGroupDataOnDemand.modifyPointGroup(PointGroup obj) {
        return false;
    }
    
    public void PointGroupDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = pointGroupService.findPointGroupEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PointGroup' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PointGroup>();
        for (int i = 0; i < 10; i++) {
            PointGroup obj = getNewTransientPointGroup(i);
            try {
                pointGroupService.savePointGroup(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
