// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.crystallography;

import com.lacunalabs.dm.data.physics.crystallography.PointGroupDataOnDemand;
import com.lacunalabs.dm.data.physics.crystallography.PointGroupIntegrationTest;
import com.lacunalabs.dm.data.repository.physics.crystallography.PointGroupService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect PointGroupIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PointGroupIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PointGroupIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private PointGroupDataOnDemand PointGroupIntegrationTest.dod;
    
    @Autowired
    PointGroupService PointGroupIntegrationTest.pointGroupService;
    
    @Test
    public void PointGroupIntegrationTest.testCountAllPointGroups() {
        Assert.assertNotNull("Data on demand for 'PointGroup' failed to initialize correctly", dod.getRandomPointGroup());
        long count = pointGroupService.countAllPointGroups();
        Assert.assertTrue("Counter for 'PointGroup' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PointGroupIntegrationTest.testFindPointGroup() {
        PointGroup obj = dod.getRandomPointGroup();
        Assert.assertNotNull("Data on demand for 'PointGroup' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PointGroup' failed to provide an identifier", id);
        obj = pointGroupService.findPointGroup(id);
        Assert.assertNotNull("Find method for 'PointGroup' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PointGroup' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PointGroupIntegrationTest.testFindAllPointGroups() {
        Assert.assertNotNull("Data on demand for 'PointGroup' failed to initialize correctly", dod.getRandomPointGroup());
        long count = pointGroupService.countAllPointGroups();
        Assert.assertTrue("Too expensive to perform a find all test for 'PointGroup', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PointGroup> result = pointGroupService.findAllPointGroups();
        Assert.assertNotNull("Find all method for 'PointGroup' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PointGroup' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PointGroupIntegrationTest.testFindPointGroupEntries() {
        Assert.assertNotNull("Data on demand for 'PointGroup' failed to initialize correctly", dod.getRandomPointGroup());
        long count = pointGroupService.countAllPointGroups();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PointGroup> result = pointGroupService.findPointGroupEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PointGroup' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PointGroup' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PointGroupIntegrationTest.testSavePointGroup() {
        Assert.assertNotNull("Data on demand for 'PointGroup' failed to initialize correctly", dod.getRandomPointGroup());
        PointGroup obj = dod.getNewTransientPointGroup(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PointGroup' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PointGroup' identifier to be null", obj.getId());
        pointGroupService.savePointGroup(obj);
        Assert.assertNotNull("Expected 'PointGroup' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PointGroupIntegrationTest.testDeletePointGroup() {
        PointGroup obj = dod.getRandomPointGroup();
        Assert.assertNotNull("Data on demand for 'PointGroup' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PointGroup' failed to provide an identifier", id);
        obj = pointGroupService.findPointGroup(id);
        pointGroupService.deletePointGroup(obj);
        Assert.assertNull("Failed to remove 'PointGroup' with identifier '" + id + "'", pointGroupService.findPointGroup(id));
    }
    
}
