// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.crystallography;

import com.lacunalabs.dm.data.physics.crystallography.ReflectionConditionDataOnDemand;
import com.lacunalabs.dm.data.physics.crystallography.ReflectionConditionIntegrationTest;
import com.lacunalabs.dm.data.repository.physics.crystallography.ReflectionConditionService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect ReflectionConditionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ReflectionConditionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ReflectionConditionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private ReflectionConditionDataOnDemand ReflectionConditionIntegrationTest.dod;
    
    @Autowired
    ReflectionConditionService ReflectionConditionIntegrationTest.reflectionConditionService;
    
    @Test
    public void ReflectionConditionIntegrationTest.testCountAllReflectionConditions() {
        Assert.assertNotNull("Data on demand for 'ReflectionCondition' failed to initialize correctly", dod.getRandomReflectionCondition());
        long count = reflectionConditionService.countAllReflectionConditions();
        Assert.assertTrue("Counter for 'ReflectionCondition' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ReflectionConditionIntegrationTest.testFindReflectionCondition() {
        ReflectionCondition obj = dod.getRandomReflectionCondition();
        Assert.assertNotNull("Data on demand for 'ReflectionCondition' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ReflectionCondition' failed to provide an identifier", id);
        obj = reflectionConditionService.findReflectionCondition(id);
        Assert.assertNotNull("Find method for 'ReflectionCondition' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ReflectionCondition' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ReflectionConditionIntegrationTest.testFindAllReflectionConditions() {
        Assert.assertNotNull("Data on demand for 'ReflectionCondition' failed to initialize correctly", dod.getRandomReflectionCondition());
        long count = reflectionConditionService.countAllReflectionConditions();
        Assert.assertTrue("Too expensive to perform a find all test for 'ReflectionCondition', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ReflectionCondition> result = reflectionConditionService.findAllReflectionConditions();
        Assert.assertNotNull("Find all method for 'ReflectionCondition' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ReflectionCondition' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ReflectionConditionIntegrationTest.testFindReflectionConditionEntries() {
        Assert.assertNotNull("Data on demand for 'ReflectionCondition' failed to initialize correctly", dod.getRandomReflectionCondition());
        long count = reflectionConditionService.countAllReflectionConditions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ReflectionCondition> result = reflectionConditionService.findReflectionConditionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ReflectionCondition' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ReflectionCondition' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ReflectionConditionIntegrationTest.testSaveReflectionCondition() {
        Assert.assertNotNull("Data on demand for 'ReflectionCondition' failed to initialize correctly", dod.getRandomReflectionCondition());
        ReflectionCondition obj = dod.getNewTransientReflectionCondition(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ReflectionCondition' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ReflectionCondition' identifier to be null", obj.getId());
        reflectionConditionService.saveReflectionCondition(obj);
        Assert.assertNotNull("Expected 'ReflectionCondition' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ReflectionConditionIntegrationTest.testDeleteReflectionCondition() {
        ReflectionCondition obj = dod.getRandomReflectionCondition();
        Assert.assertNotNull("Data on demand for 'ReflectionCondition' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ReflectionCondition' failed to provide an identifier", id);
        obj = reflectionConditionService.findReflectionCondition(id);
        reflectionConditionService.deleteReflectionCondition(obj);
        Assert.assertNull("Failed to remove 'ReflectionCondition' with identifier '" + id + "'", reflectionConditionService.findReflectionCondition(id));
    }
    
}
