// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.crystallography;

import com.lacunalabs.dm.data.physics.crystallography.SpaceGroupDataOnDemand;
import com.lacunalabs.dm.data.physics.crystallography.SpaceGroupIntegrationTest;
import com.lacunalabs.dm.data.repository.physics.crystallography.SpaceGroupService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect SpaceGroupIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SpaceGroupIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SpaceGroupIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private SpaceGroupDataOnDemand SpaceGroupIntegrationTest.dod;
    
    @Autowired
    SpaceGroupService SpaceGroupIntegrationTest.spaceGroupService;
    
    @Test
    public void SpaceGroupIntegrationTest.testCountAllSpaceGroups() {
        Assert.assertNotNull("Data on demand for 'SpaceGroup' failed to initialize correctly", dod.getRandomSpaceGroup());
        long count = spaceGroupService.countAllSpaceGroups();
        Assert.assertTrue("Counter for 'SpaceGroup' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SpaceGroupIntegrationTest.testFindSpaceGroup() {
        SpaceGroup obj = dod.getRandomSpaceGroup();
        Assert.assertNotNull("Data on demand for 'SpaceGroup' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SpaceGroup' failed to provide an identifier", id);
        obj = spaceGroupService.findSpaceGroup(id);
        Assert.assertNotNull("Find method for 'SpaceGroup' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SpaceGroup' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SpaceGroupIntegrationTest.testFindAllSpaceGroups() {
        Assert.assertNotNull("Data on demand for 'SpaceGroup' failed to initialize correctly", dod.getRandomSpaceGroup());
        long count = spaceGroupService.countAllSpaceGroups();
        Assert.assertTrue("Too expensive to perform a find all test for 'SpaceGroup', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SpaceGroup> result = spaceGroupService.findAllSpaceGroups();
        Assert.assertNotNull("Find all method for 'SpaceGroup' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SpaceGroup' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SpaceGroupIntegrationTest.testFindSpaceGroupEntries() {
        Assert.assertNotNull("Data on demand for 'SpaceGroup' failed to initialize correctly", dod.getRandomSpaceGroup());
        long count = spaceGroupService.countAllSpaceGroups();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SpaceGroup> result = spaceGroupService.findSpaceGroupEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SpaceGroup' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SpaceGroup' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SpaceGroupIntegrationTest.testSaveSpaceGroup() {
        Assert.assertNotNull("Data on demand for 'SpaceGroup' failed to initialize correctly", dod.getRandomSpaceGroup());
        SpaceGroup obj = dod.getNewTransientSpaceGroup(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SpaceGroup' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SpaceGroup' identifier to be null", obj.getId());
        spaceGroupService.saveSpaceGroup(obj);
        Assert.assertNotNull("Expected 'SpaceGroup' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SpaceGroupIntegrationTest.testDeleteSpaceGroup() {
        SpaceGroup obj = dod.getRandomSpaceGroup();
        Assert.assertNotNull("Data on demand for 'SpaceGroup' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SpaceGroup' failed to provide an identifier", id);
        obj = spaceGroupService.findSpaceGroup(id);
        spaceGroupService.deleteSpaceGroup(obj);
        Assert.assertNull("Failed to remove 'SpaceGroup' with identifier '" + id + "'", spaceGroupService.findSpaceGroup(id));
    }
    
}
