// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.crystallography;

import com.lacunalabs.dm.data.physics.crystallography.BravaisLatticeDataOnDemand;
import com.lacunalabs.dm.data.physics.crystallography.SpaceGroupDataOnDemand;
import com.lacunalabs.dm.data.physics.crystallography.UnitCell;
import com.lacunalabs.dm.data.physics.crystallography.UnitCellDataOnDemand;
import com.lacunalabs.dm.data.repository.physics.crystallography.UnitCellService;
import com.lacunalabs.dm.shared.physics.fundamental.MetaDataType;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect UnitCellDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UnitCellDataOnDemand: @Component;
    
    private Random UnitCellDataOnDemand.rnd = new SecureRandom();
    
    private List<UnitCell> UnitCellDataOnDemand.data;
    
    @Autowired
    private BravaisLatticeDataOnDemand UnitCellDataOnDemand.bravaisLatticeDataOnDemand;
    
    @Autowired
    private SpaceGroupDataOnDemand UnitCellDataOnDemand.spaceGroupDataOnDemand;
    
    @Autowired
    UnitCellService UnitCellDataOnDemand.unitCellService;
    
    public UnitCell UnitCellDataOnDemand.getNewTransientUnitCell(int index) {
        UnitCell obj = new UnitCell();
        setMetadata(obj, index);
        setMetadataType(obj, index);
        setName(obj, index);
        setSymbol(obj, index);
        return obj;
    }
    
    public void UnitCellDataOnDemand.setMetadata(UnitCell obj, int index) {
        String metadata = "metadata_" + index;
        obj.setMetadata(metadata);
    }
    
    public void UnitCellDataOnDemand.setMetadataType(UnitCell obj, int index) {
        MetaDataType metadataType = MetaDataType.class.getEnumConstants()[0];
        obj.setMetadataType(metadataType);
    }
    
    public void UnitCellDataOnDemand.setName(UnitCell obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void UnitCellDataOnDemand.setSymbol(UnitCell obj, int index) {
        String symbol = "symbol_" + index;
        if (symbol.length() > 20) {
            symbol = symbol.substring(0, 20);
        }
        obj.setSymbol(symbol);
    }
    
    public UnitCell UnitCellDataOnDemand.getSpecificUnitCell(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UnitCell obj = data.get(index);
        BigInteger id = obj.getId();
        return unitCellService.findUnitCell(id);
    }
    
    public UnitCell UnitCellDataOnDemand.getRandomUnitCell() {
        init();
        UnitCell obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return unitCellService.findUnitCell(id);
    }
    
    public boolean UnitCellDataOnDemand.modifyUnitCell(UnitCell obj) {
        return false;
    }
    
    public void UnitCellDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = unitCellService.findUnitCellEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UnitCell' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UnitCell>();
        for (int i = 0; i < 10; i++) {
            UnitCell obj = getNewTransientUnitCell(i);
            try {
                unitCellService.saveUnitCell(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
