// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.crystallography;

import com.lacunalabs.dm.data.physics.crystallography.UnitCellPhysicalPropertyDataOnDemand;
import com.lacunalabs.dm.data.physics.crystallography.UnitCellPhysicalPropertyIntegrationTest;
import com.lacunalabs.dm.data.repository.physics.crystallography.UnitCellPhysicalPropertyService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect UnitCellPhysicalPropertyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UnitCellPhysicalPropertyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UnitCellPhysicalPropertyIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private UnitCellPhysicalPropertyDataOnDemand UnitCellPhysicalPropertyIntegrationTest.dod;
    
    @Autowired
    UnitCellPhysicalPropertyService UnitCellPhysicalPropertyIntegrationTest.unitCellPhysicalPropertyService;
    
    @Test
    public void UnitCellPhysicalPropertyIntegrationTest.testCountAllUnitCellPhysicalPropertys() {
        Assert.assertNotNull("Data on demand for 'UnitCellPhysicalProperty' failed to initialize correctly", dod.getRandomUnitCellPhysicalProperty());
        long count = unitCellPhysicalPropertyService.countAllUnitCellPhysicalPropertys();
        Assert.assertTrue("Counter for 'UnitCellPhysicalProperty' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UnitCellPhysicalPropertyIntegrationTest.testFindUnitCellPhysicalProperty() {
        UnitCellPhysicalProperty obj = dod.getRandomUnitCellPhysicalProperty();
        Assert.assertNotNull("Data on demand for 'UnitCellPhysicalProperty' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UnitCellPhysicalProperty' failed to provide an identifier", id);
        obj = unitCellPhysicalPropertyService.findUnitCellPhysicalProperty(id);
        Assert.assertNotNull("Find method for 'UnitCellPhysicalProperty' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UnitCellPhysicalProperty' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UnitCellPhysicalPropertyIntegrationTest.testFindAllUnitCellPhysicalPropertys() {
        Assert.assertNotNull("Data on demand for 'UnitCellPhysicalProperty' failed to initialize correctly", dod.getRandomUnitCellPhysicalProperty());
        long count = unitCellPhysicalPropertyService.countAllUnitCellPhysicalPropertys();
        Assert.assertTrue("Too expensive to perform a find all test for 'UnitCellPhysicalProperty', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UnitCellPhysicalProperty> result = unitCellPhysicalPropertyService.findAllUnitCellPhysicalPropertys();
        Assert.assertNotNull("Find all method for 'UnitCellPhysicalProperty' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UnitCellPhysicalProperty' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UnitCellPhysicalPropertyIntegrationTest.testFindUnitCellPhysicalPropertyEntries() {
        Assert.assertNotNull("Data on demand for 'UnitCellPhysicalProperty' failed to initialize correctly", dod.getRandomUnitCellPhysicalProperty());
        long count = unitCellPhysicalPropertyService.countAllUnitCellPhysicalPropertys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UnitCellPhysicalProperty> result = unitCellPhysicalPropertyService.findUnitCellPhysicalPropertyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UnitCellPhysicalProperty' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UnitCellPhysicalProperty' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UnitCellPhysicalPropertyIntegrationTest.testSaveUnitCellPhysicalProperty() {
        Assert.assertNotNull("Data on demand for 'UnitCellPhysicalProperty' failed to initialize correctly", dod.getRandomUnitCellPhysicalProperty());
        UnitCellPhysicalProperty obj = dod.getNewTransientUnitCellPhysicalProperty(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UnitCellPhysicalProperty' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UnitCellPhysicalProperty' identifier to be null", obj.getId());
        unitCellPhysicalPropertyService.saveUnitCellPhysicalProperty(obj);
        Assert.assertNotNull("Expected 'UnitCellPhysicalProperty' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UnitCellPhysicalPropertyIntegrationTest.testDeleteUnitCellPhysicalProperty() {
        UnitCellPhysicalProperty obj = dod.getRandomUnitCellPhysicalProperty();
        Assert.assertNotNull("Data on demand for 'UnitCellPhysicalProperty' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UnitCellPhysicalProperty' failed to provide an identifier", id);
        obj = unitCellPhysicalPropertyService.findUnitCellPhysicalProperty(id);
        unitCellPhysicalPropertyService.deleteUnitCellPhysicalProperty(obj);
        Assert.assertNull("Failed to remove 'UnitCellPhysicalProperty' with identifier '" + id + "'", unitCellPhysicalPropertyService.findUnitCellPhysicalProperty(id));
    }
    
}
