// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.fundamental;

import com.lacunalabs.dm.data.physics.fundamental.BaseUnitDataOnDemand;
import com.lacunalabs.dm.data.physics.fundamental.BaseUnitIntegrationTest;
import com.lacunalabs.dm.data.repository.physics.fundamental.BaseUnitService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect BaseUnitIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BaseUnitIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BaseUnitIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private BaseUnitDataOnDemand BaseUnitIntegrationTest.dod;
    
    @Autowired
    BaseUnitService BaseUnitIntegrationTest.baseUnitService;
    
    @Test
    public void BaseUnitIntegrationTest.testCountAllBaseUnits() {
        Assert.assertNotNull("Data on demand for 'BaseUnit' failed to initialize correctly", dod.getRandomBaseUnit());
        long count = baseUnitService.countAllBaseUnits();
        Assert.assertTrue("Counter for 'BaseUnit' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BaseUnitIntegrationTest.testFindBaseUnit() {
        BaseUnit obj = dod.getRandomBaseUnit();
        Assert.assertNotNull("Data on demand for 'BaseUnit' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BaseUnit' failed to provide an identifier", id);
        obj = baseUnitService.findBaseUnit(id);
        Assert.assertNotNull("Find method for 'BaseUnit' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'BaseUnit' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BaseUnitIntegrationTest.testFindAllBaseUnits() {
        Assert.assertNotNull("Data on demand for 'BaseUnit' failed to initialize correctly", dod.getRandomBaseUnit());
        long count = baseUnitService.countAllBaseUnits();
        Assert.assertTrue("Too expensive to perform a find all test for 'BaseUnit', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<BaseUnit> result = baseUnitService.findAllBaseUnits();
        Assert.assertNotNull("Find all method for 'BaseUnit' illegally returned null", result);
        Assert.assertTrue("Find all method for 'BaseUnit' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BaseUnitIntegrationTest.testFindBaseUnitEntries() {
        Assert.assertNotNull("Data on demand for 'BaseUnit' failed to initialize correctly", dod.getRandomBaseUnit());
        long count = baseUnitService.countAllBaseUnits();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<BaseUnit> result = baseUnitService.findBaseUnitEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'BaseUnit' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'BaseUnit' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BaseUnitIntegrationTest.testSaveBaseUnit() {
        Assert.assertNotNull("Data on demand for 'BaseUnit' failed to initialize correctly", dod.getRandomBaseUnit());
        BaseUnit obj = dod.getNewTransientBaseUnit(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'BaseUnit' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'BaseUnit' identifier to be null", obj.getId());
        baseUnitService.saveBaseUnit(obj);
        Assert.assertNotNull("Expected 'BaseUnit' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BaseUnitIntegrationTest.testDeleteBaseUnit() {
        BaseUnit obj = dod.getRandomBaseUnit();
        Assert.assertNotNull("Data on demand for 'BaseUnit' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BaseUnit' failed to provide an identifier", id);
        obj = baseUnitService.findBaseUnit(id);
        baseUnitService.deleteBaseUnit(obj);
        Assert.assertNull("Failed to remove 'BaseUnit' with identifier '" + id + "'", baseUnitService.findBaseUnit(id));
    }
    
}
