// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.fundamental;

import com.lacunalabs.dm.data.physics.fundamental.CompositeParticle;
import com.lacunalabs.dm.data.physics.fundamental.CompositeParticleDataOnDemand;
import com.lacunalabs.dm.data.repository.physics.fundamental.CompositeParticleService;
import com.lacunalabs.dm.shared.physics.fundamental.MetaDataType;
import com.lacunalabs.dm.shared.physics.fundamental.ParticleType;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CompositeParticleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CompositeParticleDataOnDemand: @Component;
    
    private Random CompositeParticleDataOnDemand.rnd = new SecureRandom();
    
    private List<CompositeParticle> CompositeParticleDataOnDemand.data;
    
    @Autowired
    CompositeParticleService CompositeParticleDataOnDemand.compositeParticleService;
    
    public CompositeParticle CompositeParticleDataOnDemand.getNewTransientCompositeParticle(int index) {
        CompositeParticle obj = new CompositeParticle();
        setMass(obj, index);
        setMetadata(obj, index);
        setMetadataType(obj, index);
        setName(obj, index);
        setParticleType(obj, index);
        setSymbol(obj, index);
        return obj;
    }
    
    public void CompositeParticleDataOnDemand.setMass(CompositeParticle obj, int index) {
        BigDecimal mass = BigDecimal.valueOf(index);
        obj.setMass(mass);
    }
    
    public void CompositeParticleDataOnDemand.setMetadata(CompositeParticle obj, int index) {
        String metadata = "metadata_" + index;
        obj.setMetadata(metadata);
    }
    
    public void CompositeParticleDataOnDemand.setMetadataType(CompositeParticle obj, int index) {
        MetaDataType metadataType = MetaDataType.class.getEnumConstants()[0];
        obj.setMetadataType(metadataType);
    }
    
    public void CompositeParticleDataOnDemand.setName(CompositeParticle obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void CompositeParticleDataOnDemand.setParticleType(CompositeParticle obj, int index) {
        ParticleType particleType = ParticleType.class.getEnumConstants()[0];
        obj.setParticleType(particleType);
    }
    
    public void CompositeParticleDataOnDemand.setSymbol(CompositeParticle obj, int index) {
        String symbol = "symbol_" + index;
        if (symbol.length() > 10) {
            symbol = symbol.substring(0, 10);
        }
        obj.setSymbol(symbol);
    }
    
    public CompositeParticle CompositeParticleDataOnDemand.getSpecificCompositeParticle(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CompositeParticle obj = data.get(index);
        BigInteger id = obj.getId();
        return compositeParticleService.findCompositeParticle(id);
    }
    
    public CompositeParticle CompositeParticleDataOnDemand.getRandomCompositeParticle() {
        init();
        CompositeParticle obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return compositeParticleService.findCompositeParticle(id);
    }
    
    public boolean CompositeParticleDataOnDemand.modifyCompositeParticle(CompositeParticle obj) {
        return false;
    }
    
    public void CompositeParticleDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = compositeParticleService.findCompositeParticleEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CompositeParticle' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CompositeParticle>();
        for (int i = 0; i < 10; i++) {
            CompositeParticle obj = getNewTransientCompositeParticle(i);
            try {
                compositeParticleService.saveCompositeParticle(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
