// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.fundamental;

import com.lacunalabs.dm.data.physics.fundamental.ParticleDataOnDemand;
import com.lacunalabs.dm.data.physics.fundamental.ParticleIntegrationTest;
import com.lacunalabs.dm.data.repository.physics.fundamental.ParticleService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect ParticleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ParticleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ParticleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private ParticleDataOnDemand ParticleIntegrationTest.dod;
    
    @Autowired
    ParticleService ParticleIntegrationTest.particleService;
    
    @Test
    public void ParticleIntegrationTest.testCountAllParticles() {
        Assert.assertNotNull("Data on demand for 'Particle' failed to initialize correctly", dod.getRandomParticle());
        long count = particleService.countAllParticles();
        Assert.assertTrue("Counter for 'Particle' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ParticleIntegrationTest.testFindParticle() {
        Particle obj = dod.getRandomParticle();
        Assert.assertNotNull("Data on demand for 'Particle' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Particle' failed to provide an identifier", id);
        obj = particleService.findParticle(id);
        Assert.assertNotNull("Find method for 'Particle' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Particle' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ParticleIntegrationTest.testFindAllParticles() {
        Assert.assertNotNull("Data on demand for 'Particle' failed to initialize correctly", dod.getRandomParticle());
        long count = particleService.countAllParticles();
        Assert.assertTrue("Too expensive to perform a find all test for 'Particle', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Particle> result = particleService.findAllParticles();
        Assert.assertNotNull("Find all method for 'Particle' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Particle' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ParticleIntegrationTest.testFindParticleEntries() {
        Assert.assertNotNull("Data on demand for 'Particle' failed to initialize correctly", dod.getRandomParticle());
        long count = particleService.countAllParticles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Particle> result = particleService.findParticleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Particle' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Particle' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ParticleIntegrationTest.testSaveParticle() {
        Assert.assertNotNull("Data on demand for 'Particle' failed to initialize correctly", dod.getRandomParticle());
        Particle obj = dod.getNewTransientParticle(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Particle' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Particle' identifier to be null", obj.getId());
        particleService.saveParticle(obj);
        Assert.assertNotNull("Expected 'Particle' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ParticleIntegrationTest.testDeleteParticle() {
        Particle obj = dod.getRandomParticle();
        Assert.assertNotNull("Data on demand for 'Particle' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Particle' failed to provide an identifier", id);
        obj = particleService.findParticle(id);
        particleService.deleteParticle(obj);
        Assert.assertNull("Failed to remove 'Particle' with identifier '" + id + "'", particleService.findParticle(id));
    }
    
}
