// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.fundamental;

import com.lacunalabs.dm.data.physics.fundamental.ParticleDataOnDemand;
import com.lacunalabs.dm.data.physics.fundamental.ParticleEnumerator;
import com.lacunalabs.dm.data.physics.fundamental.ParticleEnumeratorDataOnDemand;
import com.lacunalabs.dm.data.repository.physics.fundamental.ParticleEnumeratorService;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ParticleEnumeratorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ParticleEnumeratorDataOnDemand: @Component;
    
    private Random ParticleEnumeratorDataOnDemand.rnd = new SecureRandom();
    
    private List<ParticleEnumerator> ParticleEnumeratorDataOnDemand.data;
    
    @Autowired
    private ParticleDataOnDemand ParticleEnumeratorDataOnDemand.particleDataOnDemand;
    
    @Autowired
    ParticleEnumeratorService ParticleEnumeratorDataOnDemand.particleEnumeratorService;
    
    public ParticleEnumerator ParticleEnumeratorDataOnDemand.getNewTransientParticleEnumerator(int index) {
        ParticleEnumerator obj = new ParticleEnumerator();
        setAmount(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void ParticleEnumeratorDataOnDemand.setAmount(ParticleEnumerator obj, int index) {
        Integer amount = new Integer(index);
        obj.setAmount(amount);
    }
    
    public void ParticleEnumeratorDataOnDemand.setName(ParticleEnumerator obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public ParticleEnumerator ParticleEnumeratorDataOnDemand.getSpecificParticleEnumerator(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ParticleEnumerator obj = data.get(index);
        BigInteger id = obj.getId();
        return particleEnumeratorService.findParticleEnumerator(id);
    }
    
    public ParticleEnumerator ParticleEnumeratorDataOnDemand.getRandomParticleEnumerator() {
        init();
        ParticleEnumerator obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return particleEnumeratorService.findParticleEnumerator(id);
    }
    
    public boolean ParticleEnumeratorDataOnDemand.modifyParticleEnumerator(ParticleEnumerator obj) {
        return false;
    }
    
    public void ParticleEnumeratorDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = particleEnumeratorService.findParticleEnumeratorEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ParticleEnumerator' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ParticleEnumerator>();
        for (int i = 0; i < 10; i++) {
            ParticleEnumerator obj = getNewTransientParticleEnumerator(i);
            try {
                particleEnumeratorService.saveParticleEnumerator(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
