// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.fundamental;

import com.lacunalabs.dm.data.physics.fundamental.DecimalMultiplierDataOnDemand;
import com.lacunalabs.dm.data.physics.fundamental.PhysicalPropertyType;
import com.lacunalabs.dm.data.physics.fundamental.PhysicalPropertyTypeDataOnDemand;
import com.lacunalabs.dm.data.physics.fundamental.UnitDataOnDemand;
import com.lacunalabs.dm.data.repository.physics.fundamental.PhysicalPropertyTypeService;
import com.lacunalabs.dm.shared.physics.fundamental.MetaDataType;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PhysicalPropertyTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PhysicalPropertyTypeDataOnDemand: @Component;
    
    private Random PhysicalPropertyTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<PhysicalPropertyType> PhysicalPropertyTypeDataOnDemand.data;
    
    @Autowired
    private DecimalMultiplierDataOnDemand PhysicalPropertyTypeDataOnDemand.decimalMultiplierDataOnDemand;
    
    @Autowired
    private UnitDataOnDemand PhysicalPropertyTypeDataOnDemand.unitDataOnDemand;
    
    @Autowired
    PhysicalPropertyTypeService PhysicalPropertyTypeDataOnDemand.physicalPropertyTypeService;
    
    public PhysicalPropertyType PhysicalPropertyTypeDataOnDemand.getNewTransientPhysicalPropertyType(int index) {
        PhysicalPropertyType obj = new PhysicalPropertyType();
        setMetadata(obj, index);
        setMetadataType(obj, index);
        setName(obj, index);
        setSymbol(obj, index);
        return obj;
    }
    
    public void PhysicalPropertyTypeDataOnDemand.setMetadata(PhysicalPropertyType obj, int index) {
        String metadata = "metadata_" + index;
        obj.setMetadata(metadata);
    }
    
    public void PhysicalPropertyTypeDataOnDemand.setMetadataType(PhysicalPropertyType obj, int index) {
        MetaDataType metadataType = MetaDataType.class.getEnumConstants()[0];
        obj.setMetadataType(metadataType);
    }
    
    public void PhysicalPropertyTypeDataOnDemand.setName(PhysicalPropertyType obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void PhysicalPropertyTypeDataOnDemand.setSymbol(PhysicalPropertyType obj, int index) {
        String symbol = "symbol_" + index;
        obj.setSymbol(symbol);
    }
    
    public PhysicalPropertyType PhysicalPropertyTypeDataOnDemand.getSpecificPhysicalPropertyType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PhysicalPropertyType obj = data.get(index);
        BigInteger id = obj.getId();
        return physicalPropertyTypeService.findPhysicalPropertyType(id);
    }
    
    public PhysicalPropertyType PhysicalPropertyTypeDataOnDemand.getRandomPhysicalPropertyType() {
        init();
        PhysicalPropertyType obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return physicalPropertyTypeService.findPhysicalPropertyType(id);
    }
    
    public boolean PhysicalPropertyTypeDataOnDemand.modifyPhysicalPropertyType(PhysicalPropertyType obj) {
        return false;
    }
    
    public void PhysicalPropertyTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = physicalPropertyTypeService.findPhysicalPropertyTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PhysicalPropertyType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PhysicalPropertyType>();
        for (int i = 0; i < 10; i++) {
            PhysicalPropertyType obj = getNewTransientPhysicalPropertyType(i);
            try {
                physicalPropertyTypeService.savePhysicalPropertyType(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
