// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.fundamental;

import com.lacunalabs.dm.data.physics.fundamental.PhysicalConstantDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PhysicalConstantDataOnDemand_Roo_Configurable {
    
    declare @type: PhysicalConstantDataOnDemand: @Configurable;
    
}
