// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.physics.fundamental;

import com.lacunalabs.dm.data.physics.fundamental.ScienceUnitDataOnDemand;
import com.lacunalabs.dm.data.physics.fundamental.Unit;
import com.lacunalabs.dm.data.physics.fundamental.UnitDataOnDemand;
import com.lacunalabs.dm.data.repository.physics.fundamental.UnitService;
import com.lacunalabs.dm.shared.physics.fundamental.MetaDataType;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect UnitDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UnitDataOnDemand: @Component;
    
    private Random UnitDataOnDemand.rnd = new SecureRandom();
    
    private List<Unit> UnitDataOnDemand.data;
    
    @Autowired
    private ScienceUnitDataOnDemand UnitDataOnDemand.scienceUnitDataOnDemand;
    
    @Autowired
    UnitService UnitDataOnDemand.unitService;
    
    public Unit UnitDataOnDemand.getNewTransientUnit(int index) {
        Unit obj = new Unit();
        setConversionToMultiplier(obj, index);
        setConversionToOffset(obj, index);
        setIsSIU(obj, index);
        setMetadata(obj, index);
        setMetadataType(obj, index);
        setName(obj, index);
        setSymbol(obj, index);
        return obj;
    }
    
    public void UnitDataOnDemand.setConversionToMultiplier(Unit obj, int index) {
        BigDecimal conversionToMultiplier = BigDecimal.valueOf(index);
        obj.setConversionToMultiplier(conversionToMultiplier);
    }
    
    public void UnitDataOnDemand.setConversionToOffset(Unit obj, int index) {
        BigDecimal conversionToOffset = BigDecimal.valueOf(index);
        obj.setConversionToOffset(conversionToOffset);
    }
    
    public void UnitDataOnDemand.setIsSIU(Unit obj, int index) {
        Boolean isSIU = Boolean.TRUE;
        obj.setIsSIU(isSIU);
    }
    
    public void UnitDataOnDemand.setMetadata(Unit obj, int index) {
        String metadata = "metadata_" + index;
        obj.setMetadata(metadata);
    }
    
    public void UnitDataOnDemand.setMetadataType(Unit obj, int index) {
        MetaDataType metadataType = MetaDataType.class.getEnumConstants()[0];
        obj.setMetadataType(metadataType);
    }
    
    public void UnitDataOnDemand.setName(Unit obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void UnitDataOnDemand.setSymbol(Unit obj, int index) {
        String symbol = "symbol_" + index;
        if (symbol.length() > 10) {
            symbol = symbol.substring(0, 10);
        }
        obj.setSymbol(symbol);
    }
    
    public Unit UnitDataOnDemand.getSpecificUnit(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Unit obj = data.get(index);
        BigInteger id = obj.getId();
        return unitService.findUnit(id);
    }
    
    public Unit UnitDataOnDemand.getRandomUnit() {
        init();
        Unit obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return unitService.findUnit(id);
    }
    
    public boolean UnitDataOnDemand.modifyUnit(Unit obj) {
        return false;
    }
    
    public void UnitDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = unitService.findUnitEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Unit' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Unit>();
        for (int i = 0; i < 10; i++) {
            Unit obj = getNewTransientUnit(i);
            try {
                unitService.saveUnit(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
