// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.repository.physics.solidstate;

import com.lacunalabs.dm.data.physics.solidstate.MaterialComponentOrientations;
import com.lacunalabs.dm.data.repository.physics.solidstate.MaterialComponentOrientationsRepository;
import com.lacunalabs.dm.data.repository.physics.solidstate.MaterialComponentOrientationsServiceImpl;
import java.math.BigInteger;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MaterialComponentOrientationsServiceImpl_Roo_Service {
    
    declare @type: MaterialComponentOrientationsServiceImpl: @Service;
    
    declare @type: MaterialComponentOrientationsServiceImpl: @Transactional;
    
    @Autowired
    MaterialComponentOrientationsRepository MaterialComponentOrientationsServiceImpl.materialComponentOrientationsRepository;
    
    public long MaterialComponentOrientationsServiceImpl.countAllMaterialComponentOrientationses() {
        return materialComponentOrientationsRepository.count();
    }
    
    public void MaterialComponentOrientationsServiceImpl.deleteMaterialComponentOrientations(MaterialComponentOrientations materialComponentOrientations) {
        materialComponentOrientationsRepository.delete(materialComponentOrientations);
    }
    
    public MaterialComponentOrientations MaterialComponentOrientationsServiceImpl.findMaterialComponentOrientations(BigInteger id) {
        return materialComponentOrientationsRepository.findOne(id);
    }
    
    public List<MaterialComponentOrientations> MaterialComponentOrientationsServiceImpl.findAllMaterialComponentOrientationses() {
        return materialComponentOrientationsRepository.findAll();
    }
    
    public List<MaterialComponentOrientations> MaterialComponentOrientationsServiceImpl.findMaterialComponentOrientationsEntries(int firstResult, int maxResults) {
        return materialComponentOrientationsRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void MaterialComponentOrientationsServiceImpl.saveMaterialComponentOrientations(MaterialComponentOrientations materialComponentOrientations) {
        materialComponentOrientationsRepository.save(materialComponentOrientations);
    }
    
    public MaterialComponentOrientations MaterialComponentOrientationsServiceImpl.updateMaterialComponentOrientations(MaterialComponentOrientations materialComponentOrientations) {
        return materialComponentOrientationsRepository.save(materialComponentOrientations);
    }
    
}
