// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.math.geometry;

import com.lacunalabs.dm.data.math.geometry.OrientationRelationship;
import com.lacunalabs.dm.data.math.geometry.OrientationRelationshipDataOnDemand;
import com.lacunalabs.dm.data.math.geometry.Vector3DDataOnDemand;
import com.lacunalabs.dm.data.repository.math.geometry.OrientationRelationshipService;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect OrientationRelationshipDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OrientationRelationshipDataOnDemand: @Component;
    
    private Random OrientationRelationshipDataOnDemand.rnd = new SecureRandom();
    
    private List<OrientationRelationship> OrientationRelationshipDataOnDemand.data;
    
    @Autowired
    private Vector3DDataOnDemand OrientationRelationshipDataOnDemand.vector3DDataOnDemand;
    
    @Autowired
    OrientationRelationshipService OrientationRelationshipDataOnDemand.orientationRelationshipService;
    
    public OrientationRelationship OrientationRelationshipDataOnDemand.getNewTransientOrientationRelationship(int index) {
        OrientationRelationship obj = new OrientationRelationship();
        setRotationShape2AboutAspect1(obj, index);
        setRotationShape2AboutAspect2(obj, index);
        return obj;
    }
    
    public void OrientationRelationshipDataOnDemand.setRotationShape2AboutAspect1(OrientationRelationship obj, int index) {
        BigDecimal rotationShape2AboutAspect1 = BigDecimal.valueOf(index);
        obj.setRotationShape2AboutAspect1(rotationShape2AboutAspect1);
    }
    
    public void OrientationRelationshipDataOnDemand.setRotationShape2AboutAspect2(OrientationRelationship obj, int index) {
        BigDecimal rotationShape2AboutAspect2 = BigDecimal.valueOf(index);
        obj.setRotationShape2AboutAspect2(rotationShape2AboutAspect2);
    }
    
    public OrientationRelationship OrientationRelationshipDataOnDemand.getSpecificOrientationRelationship(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        OrientationRelationship obj = data.get(index);
        BigInteger id = obj.getId();
        return orientationRelationshipService.findOrientationRelationship(id);
    }
    
    public OrientationRelationship OrientationRelationshipDataOnDemand.getRandomOrientationRelationship() {
        init();
        OrientationRelationship obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return orientationRelationshipService.findOrientationRelationship(id);
    }
    
    public boolean OrientationRelationshipDataOnDemand.modifyOrientationRelationship(OrientationRelationship obj) {
        return false;
    }
    
    public void OrientationRelationshipDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = orientationRelationshipService.findOrientationRelationshipEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'OrientationRelationship' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<OrientationRelationship>();
        for (int i = 0; i < 10; i++) {
            OrientationRelationship obj = getNewTransientOrientationRelationship(i);
            try {
                orientationRelationshipService.saveOrientationRelationship(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
