// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.math.geometry;

import com.lacunalabs.dm.data.math.geometry.Vector3DDataOnDemand;
import com.lacunalabs.dm.data.math.geometry.Vector3DIntegrationTest;
import com.lacunalabs.dm.data.repository.math.geometry.Vector3DService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect Vector3DIntegrationTest_Roo_IntegrationTest {
    
    declare @type: Vector3DIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: Vector3DIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private Vector3DDataOnDemand Vector3DIntegrationTest.dod;
    
    @Autowired
    Vector3DService Vector3DIntegrationTest.vector3DService;
    
    @Test
    public void Vector3DIntegrationTest.testCountAllVector3Ds() {
        Assert.assertNotNull("Data on demand for 'Vector3D' failed to initialize correctly", dod.getRandomVector3D());
        long count = vector3DService.countAllVector3Ds();
        Assert.assertTrue("Counter for 'Vector3D' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void Vector3DIntegrationTest.testFindVector3D() {
        Vector3D obj = dod.getRandomVector3D();
        Assert.assertNotNull("Data on demand for 'Vector3D' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Vector3D' failed to provide an identifier", id);
        obj = vector3DService.findVector3D(id);
        Assert.assertNotNull("Find method for 'Vector3D' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Vector3D' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void Vector3DIntegrationTest.testFindAllVector3Ds() {
        Assert.assertNotNull("Data on demand for 'Vector3D' failed to initialize correctly", dod.getRandomVector3D());
        long count = vector3DService.countAllVector3Ds();
        Assert.assertTrue("Too expensive to perform a find all test for 'Vector3D', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Vector3D> result = vector3DService.findAllVector3Ds();
        Assert.assertNotNull("Find all method for 'Vector3D' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Vector3D' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void Vector3DIntegrationTest.testFindVector3DEntries() {
        Assert.assertNotNull("Data on demand for 'Vector3D' failed to initialize correctly", dod.getRandomVector3D());
        long count = vector3DService.countAllVector3Ds();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Vector3D> result = vector3DService.findVector3DEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Vector3D' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Vector3D' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void Vector3DIntegrationTest.testSaveVector3D() {
        Assert.assertNotNull("Data on demand for 'Vector3D' failed to initialize correctly", dod.getRandomVector3D());
        Vector3D obj = dod.getNewTransientVector3D(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Vector3D' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Vector3D' identifier to be null", obj.getId());
        vector3DService.saveVector3D(obj);
        Assert.assertNotNull("Expected 'Vector3D' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void Vector3DIntegrationTest.testDeleteVector3D() {
        Vector3D obj = dod.getRandomVector3D();
        Assert.assertNotNull("Data on demand for 'Vector3D' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Vector3D' failed to provide an identifier", id);
        obj = vector3DService.findVector3D(id);
        vector3DService.deleteVector3D(obj);
        Assert.assertNull("Failed to remove 'Vector3D' with identifier '" + id + "'", vector3DService.findVector3D(id));
    }
    
}
