// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lacunalabs.dm.data.math.geometry;

import com.lacunalabs.dm.data.math.geometry.Vector3DDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Vector3DDataOnDemand_Roo_Configurable {
    
    declare @type: Vector3DDataOnDemand: @Configurable;
    
}
